# Generated by Django 6.0.7 on 2026-07-31 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(default='', max_length=50),
        ),
    ]
