# Generated by Django 6.0.7 on 2026-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_created_at_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
