# Generated by Django 6.0.7 on 2026-08-12 13:57

from django.db import migrations, models


def business_user_to_business(apps, schema_editor):
    """The profile type follows the API contract, which calls the role 'business'."""
    UserProfile = apps.get_model('auth_app', 'UserProfile')
    UserProfile.objects.filter(type='business_user').update(type='business')


def business_to_business_user(apps, schema_editor):
    UserProfile = apps.get_model('auth_app', 'UserProfile')
    UserProfile.objects.filter(type='business').update(type='business_user')


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=20),
        ),
        migrations.RunPython(business_user_to_business, business_to_business_user),
    ]
